# Generated by Django 3.2.8 on 2021-11-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Изображение профиля'),
        ),
    ]
