# Generated by Django 3.2.8 on 2021-10-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=154, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=154, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
                ('product_availability', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=154, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=154, null=True, verbose_name='URL')),
                ('unit', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ед. измерения')),
                ('use_filters', models.BooleanField(default=False, verbose_name='Использование в фильтрах')),
                ('type_filter', models.CharField(choices=[('custom', 'Катомный'), ('base', 'Основной')], default='base', max_length=64, verbose_name='Тип фильтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'unique_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CustomFilterTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_digit', models.FloatField(verbose_name='От')),
                ('before_digit', models.FloatField(verbose_name='До')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Кастомный фильтр №2',
                'verbose_name_plural': 'Кастомные фильтры №2',
            },
        ),
        migrations.CreateModel(
            name='CustomFilterOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessOrEqual', models.FloatField(blank=True, null=True, verbose_name='Меньше или равно')),
                ('moreOrEqual', models.FloatField(blank=True, null=True, verbose_name='Больше или равно')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Кастомный фильтр №1',
                'verbose_name_plural': 'Кастомные фильтры №1',
            },
        ),
        migrations.CreateModel(
            name='ValuesOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=154, verbose_name='Значение')),
                ('products', models.ManyToManyField(to='app_product.Product', verbose_name='Продукты')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение хакрктеристики',
                'verbose_name_plural': 'Значения характеристики',
                'unique_together': {('specification', 'value')},
            },
        ),
    ]
