# Generated by Django 3.2.8 on 2022-01-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма')),
                ('is_cart', models.BooleanField(default=True, verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина-Заказ',
                'verbose_name_plural': 'Корзины-Заказы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=154, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=154, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
                ('product_availability', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=154, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=154, unique=True, verbose_name='URL')),
                ('unit', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ед. измерения')),
                ('use_filters', models.BooleanField(default=False, verbose_name='Использование в фильтрах')),
                ('type_filter', models.CharField(choices=[('base', 'Основной'), ('custom', 'Кастомный')], default='base', max_length=64, verbose_name='Тип фильтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'unique_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ValuesOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=154, verbose_name='Значение')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_sp', to='app_product.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение хакрктеристик',
                'verbose_name_plural': 'Значения характеристик',
                'unique_together': {('specification', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзыв')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProductsInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_with_products', to='app_product.cartororder', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзинах',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(blank=True, to='app_product.ValuesOfSpecification', verbose_name='Характеристики'),
        ),
        migrations.CreateModel(
            name='PickUpPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=69, verbose_name='Область, регион')),
                ('city', models.CharField(max_length=69, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пункт получения',
                'verbose_name_plural': 'Пункты получения',
                'ordering': ['region', 'city', 'address'],
                'unique_together': {('region', 'city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_get', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='pickup', max_length=255, verbose_name='Cпособ получения')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('method_payment', models.CharField(choices=[('upon_receipt', 'При получении'), ('online', 'Онлайн')], default='upon_receipt', max_length=255, verbose_name='Способ оплаты')),
                ('order_status', models.CharField(choices=[('placed', 'Оформлен'), ('transit', 'В пути'), ('ready', 'Готов к выдаче'), ('Completed', 'Завершен')], default='placed', max_length=255, verbose_name='Статус заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.cartororder', verbose_name='заказ')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_product.pickuppoints', verbose_name='Пункт выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='cartororder',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_in_cart', to='app_product.ProductsInCart', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='CustomFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessOrEqual', models.FloatField(blank=True, null=True, verbose_name='Менее ( До )')),
                ('moreOrEqual', models.FloatField(blank=True, null=True, verbose_name='Более ( От )')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_filter', to='app_product.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Кастомный фильтр',
                'verbose_name_plural': 'Кастомные фильтры',
                'unique_together': {('specification', 'lessOrEqual', 'moreOrEqual')},
            },
        ),
    ]
