# Generated by Django 3.2.8 on 2021-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=154, unique=True, verbose_name='URL'),
        ),
    ]
