# Generated by Django 3.2.8 on 2021-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=154, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
