# Generated by Django 3.2.8 on 2021-10-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_alter_specification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesofspecification',
            name='products',
            field=models.ManyToManyField(blank=True, to='app_product.Product', verbose_name='Продукты'),
        ),
    ]
