# Generated by Django 3.2.8 on 2021-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_valuesofspecification_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuesofspecification',
            options={'verbose_name': 'Значение хакрктеристик', 'verbose_name_plural': 'Значения характеристик'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='type_filter',
            field=models.CharField(choices=[('custom', 'Кастомный'), ('base', 'Основной')], default='base', max_length=64, verbose_name='Тип фильтра'),
        ),
    ]
