# Generated by Django 3.2.8 on 2021-11-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_auto_20211110_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfilterone',
            unique_together={('specification', 'lessOrEqual', 'moreOrEqual')},
        ),
        migrations.AlterUniqueTogether(
            name='customfiltertwo',
            unique_together={('specification', 'from_digit', 'before_digit')},
        ),
    ]
