# Generated by Django 3.2.8 on 2021-11-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_alter_valuesofspecification_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilterone',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_filter', to='app_product.specification', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='customfiltertwo',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_filter', to='app_product.specification', verbose_name='Характеристика'),
        ),
    ]
