# Generated by Django 3.2.8 on 2021-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_auto_20211127_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomFilterOne',
            new_name='CustomFilter',
        ),
        migrations.AlterModelOptions(
            name='customfilter',
            options={'verbose_name': 'Кастомный фильтр', 'verbose_name_plural': 'Кастомные фильтры'},
        ),
        migrations.DeleteModel(
            name='CustomFilterTwo',
        ),
    ]
