# Generated by Django 3.2.8 on 2021-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_auto_20211127_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilter',
            name='lessOrEqual',
            field=models.FloatField(blank=True, null=True, verbose_name='Менее(До)'),
        ),
        migrations.AlterField(
            model_name='customfilter',
            name='moreOrEqual',
            field=models.FloatField(blank=True, null=True, verbose_name='Более(От)'),
        ),
    ]
