# Generated by Django 3.2.8 on 2021-11-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20211130_2159'),
        ('app_product', '0014_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cart', models.BooleanField(default=True, verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина-Заказ',
                'verbose_name_plural': 'Корзины-Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductsInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_with_products', to='app_product.cartororder', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзинах',
            },
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='cartororder',
            name='products',
            field=models.ManyToManyField(related_name='product_in_cart', to='app_product.ProductsInCart', verbose_name='Продукты'),
        ),
    ]
