# Generated by Django 3.2.8 on 2021-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_auto_20211130_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartororder',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='cartororder',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма'),
        ),
    ]
