# Generated by Django 3.2.8 on 2021-12-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0004_alter_customer_user'),
        ('app_product', '0016_auto_20211204_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('raiting', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзыв')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
