# Generated by Django 3.2.8 on 2021-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0017_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='raiting',
            new_name='rating',
        ),
    ]
