# Generated by Django 3.2.8 on 2021-12-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0018_rename_raiting_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_product.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
