# Generated by Django 3.2.8 on 2021-12-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0019_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=69, verbose_name='Область, регион')),
                ('city', models.CharField(max_length=69, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пункт получения',
                'verbose_name_plural': 'Пункты получения',
                'ordering': ['region', 'city', 'address'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_of_creation'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_get', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='pickup', max_length=255, verbose_name='Cпособ получения')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('method_payment', models.CharField(choices=[('upon_receipt', 'При получении'), ('online', 'Онлайн')], default='upon_receipt', max_length=255, verbose_name='Способ оплаты')),
                ('order_status', models.CharField(choices=[('placed', 'Оформлен'), ('transit', 'В пути'), ('ready', 'Готов к выдаче'), ('Completed', 'Завершен')], default='placed', max_length=255, verbose_name='Статус заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.cartororder', verbose_name='заказ')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_product.pickuppoints', verbose_name='Пункты выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
