# Generated by Django 3.2.8 on 2021-12-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0020_auto_20211227_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_product.pickuppoints', verbose_name='Пункт выдачи'),
        ),
    ]
