# Generated by Django 3.2.8 on 2021-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0021_alter_order_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartororder',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_in_cart', to='app_product.ProductsInCart', verbose_name='Продукты'),
        ),
    ]
